version: "3.1"
services:

  workspace:
    image: laradock/workspace:2.2-7.2
    container_name: application-workspace
    volumes:
      - .:/application:cached
    ports:
      - "14422:22"

  webserver:
    image: nginx:alpine
    container_name: application-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "14400:80"

  php-fpm:
    build: environment/php-fpm
    container_name: application-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./environment/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    container_name: application-redis
